# Testing

name: Maven and REST Assured Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Run-Rest-Assured-Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Run REST Assured Tests with Maven
      run: mvn clean test

    - name: Run REST Assured Tests and Generate Allure Report
      run: mvn clean test
      
    - name: Archive REST-Assured Allure test report
      uses: actions/upload-pages-artifact@v3
      with:
        name: REST-Assured-results
        path: allure-results

    - name: Upload REST-Assured Allure report to GitHub
      uses: actions/upload-pages-artifact@v3
      with:
        name: REST-Assured-results
        path: allure-results
